# Generated by Django 6.1 on 2026-09-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=400)),
                ('rel', models.CharField(max_length=40)),
                ('target_id', models.CharField(max_length=400)),
                ('origin', models.CharField(default='sync', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_id'], name='cache_cache_source__e169f4_idx'), models.Index(fields=['target_id'], name='cache_cache_target__51872b_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_id', 'rel', 'target_id'), name='uniq_cache_link')],
            },
        ),
        migrations.CreateModel(
            name='CacheRecord',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('body_text', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=800)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('ingested_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('has_embedding', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'type'], name='cache_cache_source_805648_idx'), models.Index(fields=['occurred_at'], name='cache_cache_occurre_3fba1e_idx'), models.Index(fields=['deleted'], name='cache_cache_deleted_40b84f_idx')],
            },
        ),
    ]
