# Generated by Django 6.1 on 2026-09-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('record_rule', 'record rule'), ('schedule', 'schedule'), ('cron', 'cron')], max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('spec', models.JSONField(default=dict)),
                ('webhook_route', models.CharField(blank=True, default='', max_length=200)),
                ('dedupe_window_s', models.IntegerField(default=3600)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('fire_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_key', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, default='', max_length=400)),
                ('attempt', models.IntegerField(default=1)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('dead', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['trigger_key', 'entity_id', 'created_at'], name='triggers_de_trigger_59bffa_idx')],
            },
        ),
    ]
