# Generated by Django 6.1 on 2026-09-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('source_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('cursor', models.CharField(blank=True, default='', max_length=500)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_ok', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('last_report', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
