# Generated by Django 6.1 on 2026-09-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_embedding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='props',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
