# Generated by Django 6.1 on 2026-09-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedCache',
            fields=[
                ('text_hmac', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
