# Generated by Django 6.1 on 2026-09-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default='You are Eunomia, a personal AI assistant that helps manage tasks, reminders, calendar events and general organisation. Be concise and proactive.')),
                ('llm_base_url', models.CharField(blank=True, default='https://api.openai.com/v1', max_length=300)),
                ('llm_model', models.CharField(blank=True, default='gpt-4o-mini', max_length=200)),
                ('llm_api_key_encrypted', models.TextField(blank=True, default='')),
                ('theme', models.JSONField(blank=True, default=dict, help_text='Arbitrary theme config consumed by the frontend, e.g. {"mode": "dark", "accent": "#0A84FF"}')),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('google', 'Google (Calendar + Gmail)'), ('up_bank', 'Up Bank'), ('pocketai', 'PocketAI')], max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
