# Generated by Django 6.1 on 2026-09-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='system_prompt',
            field=models.TextField(default='You are Eunomia, a personal AI assistant that helps manage tasks, reminders, calendar events and general organisation. Be concise and proactive. You can read upcoming calendar meetings and recent Up Bank transactions, and turn them into tasks when asked (e.g. meeting-prep tasks, bill follow-ups).'),
        ),
    ]
