# Generated by Django 6.1 on 2026-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_alter_appsettings_system_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('amount_cents', models.IntegerField(help_text='Negative = spend, positive = income')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
