# Generated by Django 6.1 on 2026-09-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0003_demotransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('attendees', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=200)),
                ('snippet', models.CharField(max_length=300)),
                ('received_at', models.DateTimeField()),
                ('unread', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_seconds', models.IntegerField()),
                ('tags', models.JSONField(default=list)),
                ('recorded_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
