# Generated by Django 6.1 on 2026-09-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_democalendarevent_demoemail_demorecording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='system_prompt',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='embedding_backend',
            field=models.CharField(choices=[('api', 'OpenAI-compatible API'), ('local', 'Local (sentence-transformers)'), ('stub', 'Stub')], default='api', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='hermes_webhook_secret_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='hermes_webhook_url',
            field=models.CharField(blank=True, default='', help_text='Base URL of the Hermes gateway webhook adapter, e.g. http://127.0.0.1:8644/webhooks', max_length=400),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pii_allowlist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pii_disabled_sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pii_min_confidence',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='sync_intervals',
            field=models.JSONField(blank=True, default=dict, help_text='{"up_bank": 900, ...} seconds per source.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='vip_senders',
            field=models.JSONField(blank=True, default=list, help_text="Sender addresses for the 'VIP email' trigger."),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='llm_base_url',
            field=models.CharField(blank=True, default='', help_text="OpenAI-compatible base URL for the 'api' embedding backend (also fits Ollama's /v1).", max_length=300),
        ),
    ]
