# Generated by Django 6.1 on 2026-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0005_remove_appsettings_llm_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='hermes_webhook_secret_encrypted',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='hermes_webhook_url',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='pii_allowlist',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='pii_disabled_sources',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='pii_min_confidence',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='vip_senders',
        ),
        migrations.AlterField(
            model_name='connector',
            name='kind',
            field=models.CharField(choices=[('google', 'Google (Calendar + Gmail)'), ('up_bank', 'Up Bank'), ('pocketai', 'PocketAI'), ('open_connector', 'Open Connector')], max_length=20, unique=True),
        ),
    ]
