# Generated by Django 6.1 on 2026-09-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0005_remove_appsettings_llm_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='user_timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone (e.g. Australia/Melbourne) used to interpret naive agent-supplied dates and render datetimes back to the agent. Set once at deployment by the installing agent; empty = UTC.', max_length=64),
        ),
    ]
