# Generated by Django 6.1 on 2026-09-07 14:23

from django.db import migrations, models


def delete_google_connector(apps, schema_editor):
    Connector = apps.get_model('connectors', 'Connector')
    Connector.objects.filter(kind='google').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0006_remove_appsettings_hermes_webhook_secret_encrypted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoCalendarEvent',
        ),
        migrations.DeleteModel(
            name='DemoEmail',
        ),
        migrations.RunPython(delete_google_connector, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='connector',
            name='kind',
            field=models.CharField(choices=[('up_bank', 'Up Bank'), ('pocketai', 'PocketAI'), ('open_connector', 'Open Connector')], max_length=20, unique=True),
        ),
    ]
