# Generated by Django 6.1 on 2026-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0006_appsettings_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='embedding_backend',
            field=models.CharField(choices=[('api', 'OpenAI-compatible API'), ('local', 'Local (sentence-transformers)'), ('stub', 'Stub')], default='stub', max_length=10),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='vip_senders',
            field=models.JSONField(blank=True, default=list, help_text="Sender addresses for the 'VIP email' reminder."),
        ),
    ]
