# Generated by Django 6.1 on 2026-09-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0007_alter_appsettings_embedding_backend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='kind',
            field=models.CharField(choices=[('google', 'Google (Calendar + Gmail)'), ('up_bank', 'Up Bank'), ('pocketai', 'PocketAI'), ('twenty', 'Twenty CRM')], max_length=20, unique=True),
        ),
    ]
