# Generated by Django 6.1 on 2026-09-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultSecret',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value_encrypted', models.TextField()),
                ('value_hmac', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('credential', 'credential'), ('pii', 'pii')], max_length=16)),
                ('type', models.CharField(max_length=40)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='masking_vau_type_e24766_idx')],
            },
        ),
    ]
