# Generated by Django 6.1 on 2026-09-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reveal', 'reveal'), ('tool_input', 'tool input'), ('outbound', 'outbound')], max_length=16)),
                ('actor', models.CharField(blank=True, default='', max_length=120)),
                ('tokens', models.JSONField(default=list)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='masking_aud_created_6e8948_idx'), models.Index(fields=['kind'], name='masking_aud_kind_529bd2_idx')],
            },
        ),
    ]
